create table if not exists records (
    id        BIGINT generated by default as identity not null,
    app       VARCHAR,
    ip        VARCHAR,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    uri       VARCHAR,
    PRIMARY KEY (id)
);